### ISSUE TITLE
Can not extract glottal features.

### ISSUE THREAD

**Issue by Xu-Shihao** [jcvasquezc/DisVoice#11]
I met a problem when I extracted glottal features, where winShift(=5)/1000*fs=0 cause the error.

So I fixed the error like this:
 #Calculate LP-residual and extract N maxima per mean-based signal determined intervals
    res = utils_gci.GetLPCresidual(x,winLen*fs/1000,winShift*fs/1000,LPC_ord, VUV_inter); 

Now the code is still not working. Can someone tell me how to fix this problem? 
![image](https://user-images.githubusercontent.com/20655000/41326847-a2e9c3e0-6ef3-11e8-9edf-97b4e994e76a.png)

I used python2.7 in Unbuntu16.04 x64.

By the way, pysptk package can not be successfully installed under python3.6 virtualenv.

Thanks and Regards
XU SHIHAO

**Comment by jcvasquezc** [comment]
Dear XU

Thank you for let us know the issue

The problem is now fixed in the new version and the glottal features are computed

Please update the files `glottal.py,` `GCI.py`, and `utils_gci.py`, or just pull the newest version, and I hope everything runs fine.

Best regards

**Comment by Xu-Shihao** [comment]
Hi

Thanks. The code is working well on your example audios.

However it still not work on my own data. Please take a look. 
![image](https://user-images.githubusercontent.com/20655000/41387439-7194acbc-6fb9-11e8-9a88-2db2023a400d.png)

Really Thanks!
Regards
XU SHIHAO

**Comment by jcvasquezc** [comment]
Hi XU

The issues are fixed in the current version of Disvoice. Please take a look whether is working ok for your data
Best

**Comment by Xu-Shihao** [comment]
Thanks for your help. 

XU SHIHAO
